<script>
  import Nav from "./components/nav.svelte";
  import Header from "./components/header.svelte";
  import Projects from "./components/Projects.svelte";
    import Footer from "./components/Footer.svelte";
</script>
<Nav />
<Header />
<main class="p-5">
  <Projects />
  <section id="ABOUT" class="rounded-lg border-2 bg-white m-5 p-5 break-all">
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa cumque excepturi incidunt placeat nesciunt et? Officia similique ut quia laudantium, praesentium doloribus culpa mollitia ullam non iure animi rem ipsum tempore optio expedita quasi dolores sit amet consequatur possimus tempora, adipisci accusantium! Repudiandae iure libero labore sunt ducimus reiciendis sint, vel maiores cumque nam facilis. Dolore perferendis a atque cupiditate optio maiores sequi consequatur aliquid totam natus voluptates corporis, ipsum, qui necessitatibus eos quos ab sint accusantium tempora placeat eveniet neque laborum aspernatur nostrum! Quidem minima officia, assumenda deserunt aperiam debitis repellendus sunt nisi porro ad saepe voluptates non, quisquam soluta nemo, quae exercitationem amet aliquam ab. Nostrum, repudiandae. Unde eos quo quasi obcaecati reiciendis iste dolore accusantium cumque? Excepturi voluptates facere consectetur porro ipsum, tempore provident, facilis asperiores dolores hic magni repellendus ea delectus suscipit reiciendis consequatur? Possimus provident assumenda enim fuga voluptatem officia, vitae ea facilis debitis quam ratione sit quibusdam. Iusto illo omnis dolores ullam natus? Natus odit rem, cumque iste deleniti nostrum voluptatem saepe fuga aperiam aliquid mollitia placeat quis dignissimos porro, nisi fugiat quidem sapiente tenetur quaerat accusantium ipsa maiores dolorum autem. Placeat eveniet laboriosam nesciunt sequi, cum temporibus, culpa aperiam sit labore provident ea dolore incidunt voluptatibus. Repellat sed nemo temporibus harum officia, architecto repudiandae fugit. Velit aliquid ex voluptates dolorem provident quos porro, tempora alias molestias at eos quas praesentium distinctio quae, error beatae architecto eligendi tenetur vel autem, ratione possimus dicta fugiat? Natus aperiam dolore esse iure eveniet, harum rem blanditiis! Ipsa minus ex animi accusamus quos! Optio delectus ratione, iusto rerum nam cum nesciunt eaque a dolor repellendus natus minus, aliquam eveniet commodi dolores dicta laudantium enim vero! Nam dolorem veniam sit mollitia eligendi. Repellendus odit praesentium, alias tempora dolore, dolorem, expedita non neque modi assumenda saepe beatae nulla incidunt animi autem? Saepe, ipsam ab atque nisi laborum iste eum corporis optio, aperiam quis facere iure vero odio labore error beatae quia! Praesentium iste dolor optio aut officia impedit ab unde. Facere quia saepe ab culpa iste, maiores inventore fuga temporibus consectetur ducimus. Quas ut necessitatibus velit aperiam iure, architecto accusamus. Similique ipsa autem itaque perspiciatis eos dolorem molestiae fugiat magni, at debitis eveniet saepe ex, deserunt esse aliquid tempora totam soluta amet repellat quam expedita rerum, delectus earum ipsam! Distinctio id perferendis dolores alias libero unde nemo voluptate amet numquam, suscipit esse doloribus illum recusandae non facilis porro. Delectus, quisquam!
  </section>
</main>
<Footer />